### ISSUE TITLE
Workflow greenfield, brownfield

### ISSUE THREAD

**Issue by cmoulliard** [gastaldi/lab-forge-swarm-keycloak#1]
As the purpose of this lab is to design a project using Swarm, Forge & Keycloak technology & the Microservices Architectural pattern, does it make sense to introduce the workflow greenfield, browfield chapter instead of developing this aspect in a distinct & separate HOL project ?

**Comment by cmoulliard** [comment]
Suggestion of @bgeorges : Create a new repo where we will elaborate such Architectural design patterns question including browfield

**Comment by cmoulliard** [comment]
Project created : https://github.com/cmoulliard/microservices-concepts-patterns/blob/master/README.adoc

**Comment by bgeorges** [comment]
Closing this
