### ISSUE TITLE
Share source of the diagrams

### ISSUE THREAD

**Issue by cmoulliard** [gastaldi/lab-forge-swarm-keycloak#2]
Can you share the source file which has been used to develop the diagrams (msademo-overall-workflow.png, msademo-greenfield-workflow.png) ? Have you developed them using Xmind, Omnigraffle ?

**Comment by bgeorges** [comment]
Done.

**Comment by cmoulliard** [comment]
I don't see any source file ....

**Comment by bgeorges** [comment]
See my comments. 

## 

Bruno Georges
+65 8218 0964

**Comment by cmoulliard** [comment]
The only info reported on this issue is "Done" without any comments but the file has not been added to the repo ?

**Comment by bgeorges** [comment]
It was just a merge conflict one my side. Images are now there.
