### ISSUE TITLE
Propose additional steps/remarks for msademo-overall-workflow

### ISSUE THREAD

**Issue by cmoulliard** [gastaldi/lab-forge-swarm-keycloak#3]
![msademo-overall-workflow](https://cloud.githubusercontent.com/assets/463790/17924791/72157bc0-69ea-11e6-99eb-38267415d269.png)

A : A refactoring step is certainly required to extract existing code of the services, repackage the services, ...
B : The step to identify the services & architectural patterns is also required prior to "create Services & assemble"
C : For a new App, the text should be "Select maven dependencies"
D : Is the wording appropriate "bare metal = runs locally the project using java -jar ?", "container = Java Container (Swarm, ...) ?, "Paas = Docker Container running in Openshift"

**Comment by bgeorges** [comment]
The diagram is updated to include the additional steps.

**Comment by bgeorges** [comment]
Looks like I didn't push the changes. Will leave this open and close when I pushed them.
