### ISSUE TITLE
Agree on use case

### ISSUE THREAD

**Issue by bgeorges** [gastaldi/lab-forge-swarm-keycloak#5]

**Comment by gastaldi** [comment]
I am unsure on how the hawkular integration should work as there is no Swarm fraction for it.

Also the image needs to be corrected: it says "Secure with Hawkular" but it should read "Secure with Keycloak" (I think @sblanc mentioned that)

**Comment by bgeorges** [comment]
I'll fix this tomorrow 

## 

Bruno Georges
+65 8218 0964

**Comment by sebastienblanc** [comment]
My idea for the JavaOne HoL is : 
- Create a bookstore app with Forge that contains : 
  - A book/Author model (title / author name) 
  - A SellingPoint Object containing location info (latitude / longitude) 
    - This part with be extracted later as a swarm service
- Scaffold AngularJS front end for this app
- Initially deploy this app as an "old school" WAR on WF
- "explode" the app into 3 different swarm apps : 
  -  A book/author service
  - A Selling point service
  - A front end (an "empty" swarm app containing just a `web-app` folder, ideally this should be a standalone webapp running nodejs, but is a bit out of scope for JavaOne audience) 
- "secure" the 3 swarm apps with KeyCloak
  - Here we introduce a 4th swarm app with the KeyCloak server
- Add Hibernate Search fraction to the Selling Point service and show geospatial queries 
  - Bonus point could be showing HB Search integration with Elastic Search 

Startring tomorrow, I will flush out all these steps including Forge commands and screenshots.

**Comment by cmoulliard** [comment]
@bgeorges & @cmoulliard discussion

```
Bruno Georges, [28 Aug 2016 15:24]: 
I think it would go well with Seb use can, we could think of a publisher that receives orders from camel to get more stocks.

Charles Moulliard, [28 Aug 2016 16:26]: 
I have already created a Web socket example with camel and/or activemq to get randomly stock quotes. This code could be reused for the hol  with some modifications

Bruno Georges, [28 Aug 2016 17:23]: 
+1

Charles Moulliard, [28 Aug 2016 17:26]: 
Here is the project —> https://github.com/FuseByExample/websocket-activemq-camel
```

**Comment by cmoulliard** [comment]
We have decided this afternoon @gastaldi, @sebastienblanc that the camel pitch will be added as bonus if we have enough time as the target date to deliver this hol is in 3 Weeks - 19/09

**Comment by bgeorges** [comment]
To summarize: we agreed on entities, attributes, workflow, keycloak to secure endpoints, hibernate search for the selling points localization service, camel end-points integration , in-memory persistence (will show SQL db as well) and hawkular APM for app performance monitoring (optional).
